;<?php die('');?>
isWindows=
enableTests=1
enableOldActionSelector=
use_error_handler=1
dbProfils="dbprofils.ini.php"
unusedModules=jacldb
trustedModules=
checkTrustedModules=
modulesPath="lib:jelix-modules/,app:modules/"
pluginsPath="app:plugins/"
timeZone="Europe/Paris"
theme=pure
charset="UTF-8"
locale=fr_FR
startAction="accueil:index"
startModule=base
[coordplugins]
auth="auth.coord.ini.php"
[tplplugins]
defaultJformsBuilder=html
[responses]
html=myHtmlResponse
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
tcpdf=jResponseTcpdf
soap=jResponseSoap
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
html.path="/home/calmacil/jelix/ffdvh/responses/myHtmlResponse.class.php"
redirect.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseBinary.class.php"
text.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseText.class.php"
cmdline.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseJsonrpc.class.php"
json.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseJson.class.php"
xmlrpc.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXmlrpc.class.php"
xul.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXul.class.php"
xuloverlay.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXulOverlay.class.php"
xuldialog.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXulDialog.class.php"
xulpage.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXulPage.class.php"
rdf.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseRdf.class.php"
xml.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXml.class.php"
zip.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseZip.class.php"
rss2.0.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseRss20.class.php"
atom1.0.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseAtom10.class.php"
css.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseCss.class.php"
ltx2pdf.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseLatexToPdf.class.php"
tcpdf.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseTcpdf.class.php"
soap.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseSoap.class.php"
htmlfragment.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseHtml.class.php"
[_coreResponses]
html=jResponseHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
tcpdf=jResponseTcpdf
soap=jResponseSoap
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
html.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseHtml.class.php"
redirect.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseBinary.class.php"
text.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseText.class.php"
cmdline.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseJsonrpc.class.php"
json.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseJson.class.php"
xmlrpc.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXmlrpc.class.php"
xul.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXul.class.php"
xuloverlay.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXulOverlay.class.php"
xuldialog.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXulDialog.class.php"
xulpage.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXulPage.class.php"
rdf.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseRdf.class.php"
xml.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseXml.class.php"
zip.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseZip.class.php"
rss2.0.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseRss20.class.php"
atom1.0.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseAtom10.class.php"
css.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseCss.class.php"
ltx2pdf.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseLatexToPdf.class.php"
tcpdf.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseTcpdf.class.php"
soap.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseSoap.class.php"
htmlfragment.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="/home/calmacil/jelix/lib/jelix/core/response/jResponseHtml.class.php"
[error_handling]
messageLogFormat="%date%\t[%code%]\t%msg%\t%file%\t%line%\n"
logFile="error.log"
email="root@localhost"
emailHeaders="Content-Type: text/plain; charset=UTF-8\nFrom: webmaster@yoursite.com\nX-Mailer: Jelix\nX-Priority: 1 (Highest)\n"
quietMessage="An error occured. Sorry for the inconvenience."
showInFirebug=
default="TRACE ECHO EXIT"
error="TRACE ECHO EXIT"
warning="TRACE ECHO"
notice="TRACE ECHO"
strict="TRACE ECHO"
deprecated=
exception=ECHO
[compilation]
checkCacheFiletime=1
force=1
[urlengine]
engine=basic_significant
enableParser=1
multiview=
scriptNameServerVariable=SCRIPT_NAME
pathInfoInQueryParameter=
basePath="/"
jelixWWWPath="/jelix/"
defaultEntrypoint=index
entrypointExtension=".php"
notfoundAct=
simple_urlengine_https=
significantFile="urls.xml"
urlScript="/index.php"
urlScriptPath="/"
urlScriptName="index.php"
urlScriptId=index
urlScriptIdenc=index
[simple_urlengine_entrypoints]
index="@classic"
xmlrpc="@xmlrpc"
jsonrpc="@jsonrpc"
rdf="@rdf"
[basic_significant_urlengine_entrypoints]
index=1
xmlrpc=1
jsonrpc=1
rdf=1
[logfiles]
default="messages.log"
[mailer]
webmasterEmail="togo.harrian@gmail.com"
webmasterName=Calmacil
mailerType=mail
hostname=
sendmailPath="/usr/sbin/sendmail"
smtpHost=localhost
smtpPort=25
smtpSecure=
smtpHelo=
smtpAuth=
smtpUsername=
smtpPassword=
smtpTimeout=10
[acl]
driver=
[acl2]
driver=db
[sessions]
start=1
shared_session=
name=
storage=
loadClasses=
[forms]
controls.datetime.input=menulists
controls.datetime.months.labels=names
datepicker=default
[datepickers]
default="jelix/js/jforms/datepickers/default/init.js"
[htmleditors]
default.engine.name=wymeditor
default.engine.file[]="jelix/jquery/jquery.js"
default.engine.file[]="jelix/wymeditor/jquery.wymeditor.js"
default.config="jelix/wymeditor/config/default.js"
default.skin.default="jelix/wymeditor/skins/default/screen.css"
[zones]
disableCache=
[classbindings]
[_allBasePath]
0="/home/calmacil/jelix/lib/jelix-modules/"
1="/home/calmacil/jelix/ffdvh/modules/"
2="/home/calmacil/jelix/ffdvh/plugins/coord/"
3="/home/calmacil/jelix/ffdvh/plugins/db/"
4="/home/calmacil/jelix/ffdvh/plugins/auth/"
5="/home/calmacil/jelix/ffdvh/plugins/tpl/"
[_modulesPathList]
jelix="/home/calmacil/jelix/lib/jelix/core-modules/jelix/"
jauth="/home/calmacil/jelix/lib/jelix-modules/jauth/"
jWSDL="/home/calmacil/jelix/lib/jelix-modules/jWSDL/"
jacl2db="/home/calmacil/jelix/lib/jelix-modules/jacl2db/"
junittests="/home/calmacil/jelix/lib/jelix-modules/junittests/"
base="/home/calmacil/jelix/ffdvh/modules/base/"
livres="/home/calmacil/jelix/ffdvh/modules/livres/"
admin="/home/calmacil/jelix/ffdvh/modules/admin/"
ffdvh="/home/calmacil/jelix/ffdvh/modules/ffdvh/"
membre="/home/calmacil/jelix/ffdvh/modules/membre/"
[_pluginsPathList_coord]
jacl="/home/calmacil/jelix/lib/jelix/plugins/coord/jacl/"
magicquotes="/home/calmacil/jelix/lib/jelix/plugins/coord/magicquotes/"
auth="/home/calmacil/jelix/lib/jelix/plugins/coord/auth/"
jacl2="/home/calmacil/jelix/lib/jelix/plugins/coord/jacl2/"
history="/home/calmacil/jelix/lib/jelix/plugins/coord/history/"
autolocale="/home/calmacil/jelix/lib/jelix/plugins/coord/autolocale/"
zendframework="/home/calmacil/jelix/lib/jelix/plugins/coord/zendframework/"
[_pluginsPathList_acl]
db="/home/calmacil/jelix/lib/jelix/plugins/acl/db/"
[_pluginsPathList_db]
intuition="/home/calmacil/jelix/lib/jelix/plugins/db/intuition/"
pgsql="/home/calmacil/jelix/lib/jelix/plugins/db/pgsql/"
mysql="/home/calmacil/jelix/lib/jelix/plugins/db/mysql/"
oci="/home/calmacil/jelix/lib/jelix/plugins/db/oci/"
sqlite="/home/calmacil/jelix/lib/jelix/plugins/db/sqlite/"
[_pluginsPathList_auth]
db="/home/calmacil/jelix/lib/jelix/plugins/auth/db/"
lds="/home/calmacil/jelix/lib/jelix/plugins/auth/lds/"
class="/home/calmacil/jelix/lib/jelix/plugins/auth/class/"
[_pluginsPathList_urls]
significant="/home/calmacil/jelix/lib/jelix/plugins/urls/significant/"
simple="/home/calmacil/jelix/lib/jelix/plugins/urls/simple/"
basic_significant="/home/calmacil/jelix/lib/jelix/plugins/urls/basic_significant/"
[_pluginsPathList_jforms]
html="/home/calmacil/jelix/lib/jelix/plugins/jforms/html/"
htmllight="/home/calmacil/jelix/lib/jelix/plugins/jforms/htmllight/"
[_tplpluginsPathList_html]
0="/home/calmacil/jelix/lib/jelix/plugins/tpl/html/"
1="/home/calmacil/jelix/ffdvh/plugins/tpl/html/"
[_tplpluginsPathList_ltx2pdf]
0="/home/calmacil/jelix/lib/jelix/plugins/tpl/ltx2pdf/"
[_tplpluginsPathList_xul]
0="/home/calmacil/jelix/lib/jelix/plugins/tpl/xul/"
[_tplpluginsPathList_common]
0="/home/calmacil/jelix/lib/jelix/plugins/tpl/common/"
1="/home/calmacil/jelix/ffdvh/plugins/tpl/common/"
[_tplpluginsPathList_xml]
0="/home/calmacil/jelix/lib/jelix/plugins/tpl/xml/"
[_tplpluginsPathList_text]
0="/home/calmacil/jelix/lib/jelix/plugins/tpl/text/"
1="/home/calmacil/jelix/ffdvh/plugins/tpl/text/"
[_pluginsPathList_acl2]
db="/home/calmacil/jelix/lib/jelix/plugins/acl2/db/"
[_trustedModules]
0=jelix
1=jauth
2=jWSDL
3=jacl2db
4=junittests
5=base
6=livres
7=admin
8=ffdvh
9=membre
